"""Add summary column to Document model

Revision ID: 73a0bc2f29b6
Revises: 36cb300794b4
Create Date: 2024-10-25 21:37:41.280522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a0bc2f29b6'
down_revision = '36cb300794b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
